module_name: Google Analytics
compatible_versions: 1.0.0+
author: thirty bees
category: statistics
tags:
  - google
  - analytics
  - google analytics
  - eu law
  - gdpr
description_short: The Google Analytics module allows you to add your Google Analytics tracking code to your website.
description: description.md
images:
  - image-1.png
license: AFL
gdpr_compliant: 1
